# Generated by Django 5.1.4 on 2025-01-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_web', '0003_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
