# Generated by Django 5.1.4 on 2025-01-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_web', '0004_product_image_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('rating', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
    ]
